import { mapObjIndexed } from 'ramda'

// TODO: Countries are not sorted by value.
export const COUNTRIES = {
  1: { country: 'None', nationality: 'None', code: '' },
  2: { country: 'Afghanistan', nationality: 'Afghan', code: 'AF' },
  3: { country: 'Albania', nationality: 'Albanian', code: 'AL' },
  4: { country: 'Algeria', nationality: 'Algerian', code: 'DZ' },
  5: { country: 'Andorra', nationality: 'Andorran', code: 'AD' },
  6: { country: 'Angola', nationality: 'Angolan', code: 'AO' },
  7: { country: 'Antigua and Barbuda', nationality: 'Antiguan', code: 'AG' },
  8: { country: 'Argentina', nationality: 'Argentinean', code: 'AR' },
  9: { country: 'Armenia', nationality: 'Armenian', code: 'AM' },
  10: { country: 'Australia', nationality: 'Australian', code: 'AU' },
  11: { country: 'Austria', nationality: 'Austrian', code: 'AT' },
  12: { country: 'Azerbaijan', nationality: 'Azerbaijani', code: 'AZ' },
  13: { country: 'Bahamas, The', nationality: 'Bahamian', code: 'BS' },
  14: { country: 'Bahrain', nationality: 'Bahraini', code: 'BH' },
  15: { country: 'Bangladesh', nationality: 'Bangladeshi', code: 'BD' },
  16: { country: 'Barbados', nationality: 'Barbadian', code: 'BB' },
  17: { country: 'Belarus', nationality: 'Belarusian', code: 'BY' },
  18: { country: 'Belgium', nationality: 'Belgian', code: 'BE' },
  19: { country: 'Belize', nationality: 'Belizean', code: 'BZ' },
  20: { country: 'Benin', nationality: 'Beninese', code: 'BJ' },
  21: { country: 'Bhutan', nationality: 'Bhutanese', code: 'BT' },
  22: { country: 'Bolivia', nationality: 'Bolivian', code: 'BO' },
  23: { country: 'Bosnia and Herzegovina', nationality: 'Bosnian', code: 'BA' },
  24: { country: 'Botswana', nationality: 'Motswana ', code: 'BW' },
  25: { country: 'Brazil', nationality: 'Brazilian', code: 'BR' },
  26: { country: 'Brunei', nationality: 'Bruneian', code: 'BN' },
  27: { country: 'Bulgaria', nationality: 'Bulgarian', code: 'BG' },
  28: { country: 'Burkina Faso', nationality: 'Burkinabe ', code: 'BF' },
  29: { country: 'Burma', nationality: 'Burmese', code: 'MM' },
  30: { country: 'Burundi', nationality: 'Burundian', code: 'BI' },
  31: { country: 'Cambodia', nationality: 'Cambodian', code: 'KH' },
  32: { country: 'Cameroon', nationality: 'Cameroonian', code: 'CM' },
  33: { country: 'Canada', nationality: 'Canadian', code: 'CA' },
  34: { country: 'Cape Verde', nationality: 'Cape Verdean', code: 'CV' },
  35: { country: 'Greece', nationality: 'Greek', code: 'GR' },
  36: { country: 'Grenada', nationality: 'Grenadian', code: 'GD' },
  37: { country: 'Guatemala', nationality: 'Guatemalan', code: 'GT' },
  38: { country: 'Guinea', nationality: 'Guinean', code: 'GN' },
  39: { country: 'Guinea-Bissau', nationality: 'Guinean', code: 'GW' },
  40: { country: 'Guyana', nationality: 'Guyanese', code: 'GY' },
  41: { country: 'Haiti', nationality: 'Haitian', code: 'HT' },
  42: { country: 'Holy See', code: 'VA' },
  43: { country: 'Honduras', nationality: 'Honduran', code: 'HN' },
  44: { country: 'Hungary', nationality: 'Hungarian', code: 'HU' },
  45: { country: 'Iceland', nationality: 'Icelandic', code: 'IS' },
  46: { country: 'India', nationality: 'Indian', code: 'IN' },
  47: { country: 'Indonesia', nationality: 'Indonesian', code: 'ID' },
  48: { country: 'Iran', nationality: 'Iranian', code: 'IR' },
  49: { country: 'Iraq', nationality: 'Iraqi', code: 'IQ' },
  50: { country: 'Ireland', nationality: 'Irish', code: 'IE' },
  51: { country: 'Israel', nationality: 'Israeli', code: 'IL' },
  52: { country: 'Italy', nationality: 'Italian', code: 'IT' },
  53: { country: 'Central African Republic', nationality: 'Central African', code: 'CF' },
  54: { country: 'Chad', nationality: 'Chadian', code: 'TD' },
  55: { country: 'Chile', nationality: 'Chilean', code: 'CL' },
  56: { country: 'China', nationality: 'Chinese', code: 'CN' },
  57: { country: 'South Sudan', nationality: 'South Sudanese', code: 'SS' },
  58: { country: 'Comoros', nationality: 'Comoran', code: 'KM' },
  59: { country: 'Congo, Republic of the', nationality: 'Congolese', code: 'CG' },
  60: { country: 'Congo: { Democratic Republic of the', nationality: 'Congolese', code: 'CD' },
  61: { country: 'Costa Rica', nationality: 'Costa Rican', code: 'CR' },
  62: { country: "Côte d'Ivoire", nationality: 'Ivoirian', code: 'CI' },
  63: { country: 'Croatia', nationality: 'Croatian', code: 'HR' },
  64: { country: 'Cuba', nationality: 'Cuban', code: 'CU' },
  65: { country: 'Cyprus', nationality: 'Cypriot', code: 'CY' },
  66: { country: 'Czech Republic', nationality: 'Czech', code: 'CZ' },
  67: { country: 'Denmark', nationality: 'Dane', code: 'Dk' },
  68: { country: 'Djibouti', nationality: 'Djiboutian', code: 'DJ' },
  69: { country: 'Dominica', nationality: 'Dominican', code: 'DM' },
  70: { country: 'Dominican Republic', nationality: 'Dominican', code: 'DO' },
  71: { country: 'Ecuador', nationality: 'Ecuadorian', code: 'EC' },
  72: { country: 'Egypt', nationality: 'Egyptian', code: 'EG' },
  73: { country: 'El Salvador', nationality: 'Salvadoran', code: 'SV' },
  74: { country: 'Equatorial Guinea', nationality: 'Equatorial Guinean', code: 'GQ' },
  75: { country: 'Eritrea', nationality: 'Eritrean', code: 'ER' },
  76: { country: 'Estonia', nationality: 'Estonian', code: 'EE' },
  77: { country: 'Ethiopia', nationality: 'Ethiopian', code: 'ET' },
  78: { country: 'Fiji', nationality: 'Fijian', code: 'FJ' },
  79: { country: 'Finland', nationality: 'Finnish', code: 'FI' },
  80: { country: 'France', nationality: 'French', code: 'FR' },
  81: { country: 'Gabon', nationality: 'Gabonese', code: 'GA' },
  82: { country: 'Gambia, The', nationality: 'Gambian', code: 'GM' },
  83: { country: 'Georgia', nationality: 'Georgian', code: 'GE' },
  84: { country: 'Germany', nationality: 'German', code: 'DE' },
  85: { country: 'Ghana', nationality: 'Ghanaian', code: 'GH' },
  86: { country: 'Jamaica', nationality: 'Jamaican', code: 'JM' },
  87: { country: 'Japan', nationality: 'Japanese', code: 'JP' },
  88: { country: 'Jordan', nationality: 'Jordanian', code: 'JO' },
  89: { country: 'Kazakhstan', nationality: 'Kazakhstani', code: 'KZ' },
  90: { country: 'Kenya', nationality: 'Kenyan', code: 'KE' },
  91: { country: 'Kiribati', nationality: 'I-Kiribati', code: 'KI' },
  92: { country: 'Korea, North', nationality: 'North Korean', code: 'KP' },
  93: { country: 'Korea, South', nationality: 'South Korean', code: 'KR' },
  94: { country: 'Kuwait', nationality: 'Kuwaiti', code: 'KW' },
  95: { country: 'Kyrgyzstan', nationality: 'Kyrgyzstani', code: 'KG' },
  96: { country: 'Laos', nationality: 'Laotian', code: 'LA' },
  97: { country: 'Latvia', nationality: 'Latvian', code: 'LV' },
  98: { country: 'Lebanon', nationality: 'Lebanese', code: 'LB' },
  99: { country: 'Lesotho', nationality: 'Basotho', code: 'LS' },
  100: { country: 'Liberia', nationality: 'Liberian', code: 'LR' },
  101: { country: 'Libya', nationality: 'Libyan', code: 'LY' },
  102: { country: 'Liechtenstein', nationality: 'Liechtensteiner', code: 'LI' },
  103: { country: 'Lithuania', nationality: 'Lithuanian', code: 'LT' },
  104: { country: 'Luxembourg', nationality: 'Luxembourger', code: 'LU' },
  105: {
    country: 'Macedonia, The Former Yugoslav Republic of',
    nationality: 'Macedonian',
    code: 'MK'
  },
  106: { country: 'Madagascar', nationality: 'Malagasy', code: 'MG' },
  107: { country: 'Malawi', nationality: 'Malawian', code: 'MW' },
  108: { country: 'Malaysia', nationality: 'Malaysian', code: 'MY' },
  109: { country: 'Maldives', nationality: 'Maldivan', code: 'MV' },
  110: { country: 'Mali', nationality: 'Malian', code: 'ML' },
  111: { country: 'Malta', nationality: 'Maltese', code: 'MT' },
  112: { country: 'Marshall Islands', nationality: 'Marshallese', code: 'MH' },
  113: { country: 'Mauritania', nationality: 'Mauritanian', code: 'MR' },
  114: { country: 'Mauritius', nationality: 'Mauritian', code: 'MU' },
  115: { country: 'Mexico', nationality: 'Mexican', code: 'MX' },
  116: { country: 'Micronesia, Federated States of', nationality: 'Micronesian', code: 'FM' },
  117: { country: 'Moldova', nationality: 'Moldovan', code: 'MD' },
  118: { country: 'Monaco', nationality: 'Monacan', code: 'MC' },
  119: { country: 'Mongolia', nationality: 'Mongolian', code: 'MN' },
  120: { country: 'Seychelles', nationality: 'Seychellois', code: 'SC' },
  121: { country: 'Sierra Leone', nationality: 'Sierra Leonean', code: 'SL' },
  122: { country: 'Singapore', nationality: 'Singaporean', code: 'SG' },
  123: { country: 'Slovakia', nationality: 'Slovakian', code: 'Sk' },
  124: { country: 'Slovenia', nationality: 'Slovenian', code: 'SI' },
  125: { country: 'Solomon Islands', nationality: 'Solomon Islander', code: 'SB' },
  126: { country: 'Somalia', nationality: 'Somali', code: 'SO' },
  127: { country: 'South Africa', nationality: 'South African', code: 'ZA' },
  128: { country: 'Spain', nationality: 'Spanish', code: 'ES' },
  129: { country: 'Sri Lanka', nationality: 'Sri Lankan', code: 'LK' },
  130: { country: 'Sudan', nationality: 'Sudanese', code: 'SD' },
  131: { country: 'Suriname', nationality: 'Surinamer', code: 'SR' },
  132: { country: 'Swaziland', nationality: 'Swazi', code: 'SZ' },
  133: { country: 'Sweden', nationality: 'Swedish', code: 'SE' },
  134: { country: 'Switzerland', nationality: 'Swiss', code: 'CH' },
  135: { country: 'Syria', nationality: 'Syrian', code: 'SY' },
  136: { country: 'Tajikistan', nationality: 'Tajik', code: 'TJ' },
  137: { country: 'Tanzania', nationality: 'Tanzanian', code: 'TZ' },
  138: { country: 'Thailand', nationality: 'Thai', code: 'TH' },
  139: { country: 'Morocco', nationality: 'Moroccan', code: 'MA' },
  140: { country: 'Mozambique', nationality: 'Mozambican', code: 'MZ' },
  141: { country: 'Namibia', nationality: 'Namibian', code: 'NA' },
  142: { country: 'Nauru', nationality: 'Nauruan', code: 'NR' },
  143: { country: 'Nepal', nationality: 'Nepalese', code: 'NP' },
  144: { country: 'Netherlands', nationality: 'Dutch', code: 'NL' },
  145: { country: 'New Zealand', nationality: 'New Zealander', code: 'NZ' },
  146: { country: 'Nicaragua', nationality: 'Nicaraguan', code: 'NI' },
  147: { country: 'Niger', nationality: 'Nigerien', code: 'NE' },
  148: { country: 'Nigeria', nationality: 'Nigerian', code: 'NG' },
  149: { country: 'Norway', nationality: 'Norwegian', code: 'NO' },
  150: { country: 'Oman', nationality: 'Omani', code: 'OM' },
  151: { country: 'Pakistan', nationality: 'Pakistani', code: 'PK' },
  152: { country: 'Palau', nationality: 'Palauan', code: 'PW' },
  153: { country: 'Panama', nationality: 'Panamanian', code: 'PA' },
  154: { country: 'Papua New Guinea', nationality: 'Papua New Guinean', code: 'PG' },
  155: { country: 'Paraguay', nationality: 'Paraguayan', code: 'PY' },
  156: { country: 'Peru', nationality: 'Peruvian', code: 'PE' },
  157: { country: 'Philippines', nationality: 'Filipino', code: 'PH' },
  158: { country: 'Poland', nationality: 'Polish', code: 'PL' },
  159: { country: 'Portugal', nationality: 'Portuguese', code: 'PT' },
  160: { country: 'Qatar', nationality: 'Qatari', code: 'QA' },
  161: { country: 'Romania', nationality: 'Romanian', code: 'RO' },
  162: { country: 'Russia', nationality: 'Russian', code: 'RU' },
  163: { country: 'Rwanda', nationality: 'Rwandan', code: 'RW' },
  164: { country: 'Saint Kitts and Nevis', nationality: 'Kittian and Nevisian', code: 'KN' },
  165: { country: 'Saint Lucia', nationality: 'Saint Lucian', code: 'LC' },
  166: { country: 'Saint Vincent and the Grenadines', code: 'VC' },
  167: { country: 'Samoa', nationality: 'Samoan', code: 'WS' },
  168: { country: 'San Marino', nationality: 'Sammarinese', code: 'SM' },
  169: { country: 'Sao Tome and Principe', nationality: 'Sao Tomean', code: 'ST' },
  170: { country: 'Saudi Arabia', nationality: 'Saudi Arabian', code: 'SA' },
  171: { country: 'Senegal', nationality: 'Senegalese', code: 'SN' },
  172: { country: 'Togo', nationality: 'Togolese', code: 'TG' },
  173: { country: 'Tonga', nationality: 'Tongan', code: 'TO' },
  174: { country: 'Trinidad and Tobago', code: 'TT' },
  175: { country: 'Tunisia', nationality: 'Tunisian', code: 'TN' },
  176: { country: 'Turkey', nationality: 'Turkish', code: 'TR' },
  177: { country: 'Turkmenistan', nationality: 'Turkmen', code: 'TM' },
  178: { country: 'Tuvalu', nationality: 'Tuvaluan', code: 'TV' },
  179: { country: 'Uganda', nationality: 'Ugandan', code: 'UG' },
  180: { country: 'Ukraine', nationality: 'Ukranian', code: 'UA' },
  181: { country: 'United Arab Emirates', nationality: 'Emirian', code: 'AE' },
  182: { country: 'United Kingdom', nationality: 'British', code: 'GB' },
  183: { country: 'United States of America', nationality: 'American', code: 'US' },
  184: { country: 'Uruguay', nationality: 'Uruguayan', code: 'UY' },
  185: { country: 'Uzbekistan', nationality: 'Uzbekistani', code: 'UZ' },
  186: { country: 'Vanuatu', nationality: 'Ni-Vanuatu', code: 'VU' },
  187: { country: 'Venezuela', nationality: 'Venezuelan', code: 'VE' },
  188: { country: 'Vietnam', nationality: 'Vietnamese', code: 'VN' },
  189: { country: 'Yemen', nationality: 'Yemeni', code: 'YE' },
  190: { country: 'Yugoslavia', nationality: 'Yugoslavian', code: 'YU' },
  191: { country: 'Zambia', nationality: 'Zambian', code: 'ZM' },
  192: { country: 'Zimbabwe', nationality: 'Zimbabwean', code: 'ZW' },
  193: { country: 'Aruba', nationality: 'Aruban', code: 'AW' },
  194: { country: 'Bermuda', nationality: 'Bermudan', code: 'BM' },
  195: { country: 'Hong Kong', nationality: 'Chinese/Hong Kong', code: 'HK' },
  196: { country: 'Macau', nationality: 'Chinese', code: 'MO' },
  197: { country: 'Cook Islands', nationality: 'Cook Islander', code: 'CK' },
  198: { country: 'East Timor', nationality: 'Timorese', code: 'TL' },
  199: { country: 'Netherlands Antilles', nationality: 'Dutch Antillean', code: 'NL' },
  200: { country: 'Serbia', nationality: 'Serb', code: 'RS' },
  201: { country: 'Taiwan', nationality: 'Taiwanese', code: 'TW' },
  202: { country: 'British Virgin Islands', nationality: 'British Virgin Islander', code: 'VG' },
  203: { country: 'Gibraltar', nationality: 'Gibraltarian', code: 'GI' },
  204: { country: 'United States Virgin Islands', nationality: 'Virgin Islander', code: 'VI' },
  205: { country: 'Greenland', nationality: 'Greenlandic', code: 'GL' },
  206: { country: 'Norfolk Island', nationality: 'Norfolk Islander', code: 'NF' },
  207: { country: 'New Caledonia', code: 'NC' },
  208: { country: 'Western Sahara', code: 'EH' },
  209: { country: 'Montserrat', nationality: 'Montserratian', code: 'MS' },
  210: { country: 'Guam', nationality: 'Guamanian', code: 'GU' },
  211: { country: 'Martinique', nationality: 'Martiniquais', code: 'MQ' },
  212: { country: 'French Polynesia', nationality: 'French Polynesian', code: 'PF' },
  213: { country: 'American Samoa', nationality: 'American Samoan', code: 'AS' },
  214: { country: 'Puerto Rico', nationality: 'Puerto Rican', code: 'PR' },
  215: { country: 'Turks and Caicos Islands', code: 'TC' },
  216: { country: 'Northern Mariana Islands', code: 'MP' },
  217: { country: 'Faroe Islands', nationality: 'Faroese', code: 'FO' },
  218: { country: 'Anguilla', nationality: 'Anguillan', code: 'AI' },
  219: { country: 'Guadeloupe', nationality: 'Guadeloupian', code: 'GP' },
  220: { country: 'French Guiana', nationality: 'French Guianese', code: 'GF' },
  221: { country: 'Mayotte', code: 'YT' },
  222: { country: 'Niue', nationality: 'Niuean', code: 'NU' },
  223: { country: 'Cayman Islands, The', nationality: 'Caymanian', code: 'KY' },
  224: { country: 'Myanmar', nationality: 'Myanmarese', code: 'MM' },
  225: { country: 'Vatican City', code: 'VA' },
  227: { country: 'Gaza Strip' },
  228: { country: 'West Bank' },
  229: { country: 'Colombia', nationality: 'Colombian', code: 'CO' },
  231: { country: 'Wallis and Futuna', code: 'WF' },
  232: { country: 'Saint Pierre and Miquelon', code: 'PM' },
  233: { country: 'Reunion', code: 'RE' },
  234: { country: 'Isle of Man', nationality: 'Manx', code: 'IM' },
  235: { country: 'St. Maarten' },
  236: { country: 'Guernsey', nationality: 'Channel Islander', code: 'GG' },
  238: { country: 'Jersey', code: 'JE' },
  239: { country: 'Corsica', nationality: 'Corsican' },
  240: { country: 'Montenegro', nationality: 'Montenegrin', code: 'ME' },
  241: { country: 'Kosovo', nationality: 'Kosovan', code: 'RS' },
  242: { country: 'Palestine', nationality: 'Palestinian', code: 'PS' }
}

/*
NATIONALITIES:
-------------
{ '1': 'None',
  '2': 'Afghan',
  '3': 'Albanian',
  ...}
*/
// TODO: Nationalities are not sorted by value but by key. Which seems not correct on the UI.
export const NATIONALITIES = mapObjIndexed<{ nationality: string; country: string }, string>(
  country => country.nationality || country.country,
  COUNTRIES
)

/*
COUNTRYLIST:
-------------
{ '1': 'None',
  '2': 'Afghanistan',
  '3': 'Albania',
  ...}
*/
export const COUNTRYLIST = mapObjIndexed<{ nationality: string; country: string }, string>(
  country => country.country,
  COUNTRIES
)
